TCSDB/urls.py
# from django.contrib import admin
from django.urls import re_path,include
from TCSDB import views
from utils import get_code_img
from utils.auth_token import LoginAuth
urlpatterns = [
    # path('admin/', admin.site.urls),
    re_path(r'^rbac/',include('rbac.urls')),
    re_path(r'^monitor/',include('monitor.urls')),
    re_path(r'^testcase/',include('testcase.urls')),
    re_path(r'^cccs/',include('cccs.urls')),
    re_path(r'^result/',include('result.urls')),
    re_path(r'^api/auth/', LoginAuth.as_view()),
    re_path(r'^login/', views.login),
    re_path(r'^get_code/', get_code_img.get_code),
    re_path(r'^logout/', views.logout),
    re_path(r'^index/', views.index),
    re_path(r'^index_v3/', views.index_v3),
    re_path(r'^403/', views.forbidden),
    re_path(r'^$', views.index),
]

handler404 = 'TCSDB.views.page_not_found'

cccs/urls.py
from django.urls import path,re_path
from cccs import views
from cccs import api

urlpatterns = [
    re_path(r'^api/add_cycle/$', api.AddTestCycle.as_view()),
    re_path(r'^api/add_plan/$', api.AddCaseIntoPlan.as_view()),
    re_path(r'^api/add_run/$', api.AddTestRun.as_view()),
    re_path(r'^api/start_run/$', api.StartTestRun.as_view()),
    re_path(r'^api/stop_run/$', api.StopTestRun.as_view()),
    re_path(r'^api/get_cycle/$', api.GetTestCycle.as_view()),
    re_path(r'^api/get_cases/$', api.GetCycleCaseList.as_view()),
    re_path(r'^api/get_run/$', api.GetTestRunInfo.as_view()),
    re_path(r'^api/find_cycle/$', api.FindTestCycle.as_view()),
    re_path(r'^api/find_run/$', api.FindTestRun.as_view()),
    re_path(r'^api/add_comment/$', api.AddTRComments.as_view()),
    re_path(r'^api/change_cyc_status/$', api.ChgCycleStatus.as_view()),
    re_path(r'^api/change_plc_status/$', api.ChgPlanCaseStatus.as_view()),

    re_path(r'^test_cycles$', views.test_cycles),
    re_path(r'^test_cycles/add/$', views.add_test_cycle),
    re_path(r'^test_cycles/update/$', views.update_test_cycle),
    re_path(r'^test_plans/(?P<tc_id>\d*)/$', views.test_plans),
    re_path(r'^test_plans/add/$', views.add_test_plan),
    re_path(r'^test_plans/update/$', views.update_test_plan),
    re_path(r'^run_records/(?P<tc_id>\d*)/(?P<t_status>\w*)/', views.run_records),
    re_path(r'^test_run/add/$', views.add_test_run),
    re_path(r'^test_run/update/$', views.update_test_run),
    re_path(r'^test_run/del/$', views.del_test_run),
    re_path(r'^test_actions/(?P<tc_id>\d*)/(?P<tp_id>\d*)/', views.actions),
]

cccs/models.py
from django.db import models

class TestCycle(models.Model):
    '''
    TestCycle表
    '''
    Project = models.CharField('项目名称', max_length=32, null=True, blank=True)
    CycleName = models.CharField('TestCycle名称', max_length=32)
    CycleLevel = models.CharField('Cycle等级', max_length=16, null=True, blank=True) # DRT,MRT,BRT,SMK,BCI,BVT,SVT
    Status = models.CharField('Cycle状态',max_length=16,null=True,blank=True) # ACTIVE，INACTIVE
    Created = models.DateTimeField('创建日期',auto_now_add=True)
    TriggeredTotal = models.IntegerField('共计被触发次数',default=0)
    LastTriggered = models.DateTimeField('最近一次触发时间	', null=True,blank=True)

    def __str__(self):
        return self.CycleName

    def atr(self):
        return self.testrun_set.count()

    def ntr(self):
        return self.testrun_set.filter(Status='NOTSTART').count()

    def ftr(self):
        return self.testrun_set.filter(Status='FINISHED').count()

    def etr(self):
        return self.testrun_set.filter(Status='FAILED').count()

    def ctr(self):
        return self.testrun_set.filter(Status='CANCELED').count()

    def rtr(self):
        return self.testrun_set.filter(Status='RUNNING').count()

class TestPlan(models.Model):
    '''
    TestPlan表
    '''
    CaseName = models.CharField('TestCase名称', max_length=64)
    CycleID = models.ForeignKey(verbose_name='TestCycle ID', to='TestCycle',
                                on_delete=models.SET_NULL,null=True, blank=True)
    Created = models.DateTimeField('创建日期',auto_now_add=True)
    Status = models.CharField('Case在Plan中的状态',max_length=16,null=True,blank=True) # ACTIVE，INACTIVE
    LoopCnt = models.IntegerField('重复运行次数',null=True,blank=True)

    def __str__(self):
        return self.CaseName

class TestRun(models.Model):
    '''
    TestRun表
    '''
    TestRunName = models.CharField('TestRun名称', max_length=32, unique=True)
    TriggerTime = models.DateTimeField('计划触发时间',null=True,blank=True)
    StartTime = models.DateTimeField('开始时间',null=True,blank=True)
    EndTime = models.DateTimeField('结束时间',null=True,blank=True)
    Status = models.CharField('状态', max_length=16, default='NOTSTART')  # NOTSTART，RUNNING，CANCELED，FINISHED
    TCID = models.ForeignKey(verbose_name='TestCycle ID', to='TestCycle',
                             on_delete=models.SET_NULL,null=True, blank=True)
    JIRAID = models.CharField('对应的JIRA ID',max_length=16,null=True,blank=True)
    DUTGRPID = models.IntegerField('DUT Group ID',null=True,blank=True)
    FWPkgName = models.CharField('FW Package Name', max_length=16, null=True, blank=True)
    SrtPkgName = models.CharField('Script Package Name', max_length=16, null=True, blank=True)
    Comments = models.TextField('备注信息	',null=True, blank=True)

class TestAction(models.Model):
    '''
    操作记录表
    '''
    ActionChoice = (
        (1,"TestCycle"),
        (2,"TestPlan"),
    )
    ActionType = models.IntegerField(choices=ActionChoice,default=1)
    OriginalVal = models.CharField('原值',max_length=16, null=True, blank=True)
    NewVal = models.CharField('新值',max_length=16, null=True, blank=True)
    ActionTime = models.DateTimeField('操作日期时间',auto_now_add=True)
    ActionOP = models.CharField('操作者',max_length=32,null=True,blank=True)
    PlanID = models.ForeignKey(to='TestPlan',on_delete=models.SET_NULL,null=True, blank=True)
    CycleID = models.ForeignKey(to='TestCycle',on_delete=models.SET_NULL,null=True, blank=True)

cccs/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
import json
import copy
import traceback
import datetime
from utils.pagination import Pagination
from cccs.models import *
from django.db.models import Q

def init_paginaion(request,queryset):
    # 初始化分页器
    query_params = copy.deepcopy(request.GET)  # QueryDict
    current_page = request.GET.get('page', 1)
    # per_page = config.per_page
    # pager_page_count = config.pager_page_count
    if isinstance(queryset,list):
        all_count = len(queryset)
    else:
        all_count = queryset.count()
    base_url = request.path_info
    page_obj = Pagination(current_page, all_count, base_url, query_params)
    query_set = queryset[page_obj.start:page_obj.end]
    page_html = page_obj.page_html()

    return query_set,page_html

def test_cycles(request):
    '''
    test_cycle列表
    :param request:
    :return:
    '''
    if request.method == "GET":
        page = request.GET.get("page")
        status = request.GET.get("status", "")
        message = request.GET.get("message", "")
        if status.isdigit():
            result = {"code":int(status),"message":message}
        search_q = request.GET.get('q','')

        queryset = TestCycle.objects.filter(Q(Q(CycleName__contains=search_q) |
                                           Q(Project__contains=search_q) |
                                           Q(Status__contains=search_q) |
                                           Q(CycleLevel__contains=search_q))
                                          ).distinct().order_by('-id')
        queryset, page_html = init_paginaion(request, queryset)

        return render(request,'cccs/test_cycles.html',locals())

def add_test_cycle(request):
    if request.method == "POST":
        cycle_name = request.POST.get("CycleName")
        project = request.POST.get("Project")
        cycle_level = request.POST.get("CycleLevel")
        page = request.POST.get("page")
        if cycle_name:
            try:
                TestCycle.objects.create(CycleName=cycle_name,Project=project,CycleLevel=cycle_level)
                result = {"code": 0, "message": "TestCycle创建成功!"}
            except Exception as e:
                result = {"code": 1, "message": str(e)}
        else:
            result = {"code": 1, "message": "必须指定名称!"}
        return HttpResponseRedirect('/cccs/test_cycles?status={0}&message={1}&page={2}'.
                                    format(result.get("code", ""),
                                           result.get("message", ""),
                                           page))

def update_test_cycle(request):
    '''
    更新TestCycle
    :param request:
    :return:
    '''
    if request.method == "GET":
        tid = request.GET.get('tid',None)
        tc_obj = TestCycle.objects.filter(id=tid)
        tc_dict = tc_obj.values('id','CycleName','Project','CycleLevel','Status').first()
        # print(tc_dict)
        return HttpResponse(json.dumps(dict(tc_dict)))

    elif request.method == "POST":
        tid = request.POST.get("id")
        cycle_name = request.POST.get("CycleName",None)
        project = request.POST.get("Project",None)
        cycle_level = request.POST.get("CycleLevel",None)
        status = request.POST.get("Status",None)
        status = "ACTIVE" if status == 'on' else "INACTIVE"

        page = request.POST.get("page")

        form_data = {
            'CycleName':cycle_name,
            'Project':project,
            'CycleLevel':cycle_level,
            'Status':status,
        }

        tc_obj = TestCycle.objects.get(id=tid)
        try:
            for k ,v in form_data.items():
                setattr(tc_obj,k,v)
                tc_obj.save()
            result = {"code": 0, "message": "TestCycle更新成功！"}
        except Exception as e:
            print(e)
            result = {"code": 1, "message": str(e)}

        return HttpResponseRedirect('/cccs/test_cycles?status={0}&message={1}&page={2}'.
                            format(result.get("code", ""),
                                   result.get("message", ""),
                                   page))


def test_plans(request,tc_id=""):
    '''
    test_plan列表
    :param request:
    :return:
    '''
    if request.method == "GET":
        page = request.GET.get("page")
        status = request.GET.get("status", "")
        message = request.GET.get("message", "")
        if status.isdigit():
            result = {"code":int(status),"message":message}
        search_q = request.GET.get('q','')
        tc_id = tc_id
        tc_obj = TestCycle.objects.get(id=tc_id)
        queryset = TestPlan.objects.filter(Q(Q(CaseName__contains=search_q) |
                                           Q(Status__contains=search_q))
                                          ,CycleID=tc_obj).distinct().order_by('-id')
        queryset, page_html = init_paginaion(request, queryset)

        return render(request,'cccs/test_plans.html',locals())

def add_test_plan(request):
    if request.method == "POST":
        case_name = request.POST.get("CaseName")
        loop_cnt = request.POST.get("LoopCnt")
        tc_id = request.POST.get("tc_id")
        page = request.POST.get("page")
        if case_name:
            try:
                TestPlan.objects.create(CaseName=case_name,LoopCnt=loop_cnt,CycleID_id=tc_id)
                result = {"code": 0, "message": "TestPlan创建成功!"}
            except Exception as e:
                result = {"code": 1, "message": str(e)}
        else:
            result = {"code": 1, "message": "必须指定名称!"}
        return HttpResponseRedirect('/cccs/test_plans/{3}/?status={0}&message={1}&page={2}'.
                                    format(result.get("code", ""),
                                           result.get("message", ""),
                                           page,tc_id))

def update_test_plan(request):
    '''
    更新TestCycle
    :param request:
    :return:
    '''
    if request.method == "GET":
        tid = request.GET.get('tid',None)
        tp_obj = TestPlan.objects.filter(id=tid)
        tp_dict = tp_obj.values('id','CaseName','LoopCnt','Status').first()
        # print(tp_dict)
        return HttpResponse(json.dumps(dict(tp_dict)))

    elif request.method == "POST":
        tc_id = request.POST.get("tc_id")
        tid = request.POST.get("id")
        case_name = request.POST.get("CaseName",None)
        loop_cnt = request.POST.get("LoopCnt",None)
        status = request.POST.get("Status",None)
        status = "ACTIVE" if status == 'on' else "INACTIVE"

        page = request.POST.get("page")

        form_data = {
            'CaseName':case_name,
            'LoopCnt':loop_cnt,
            'Status':status,
        }

        tp_obj = TestPlan.objects.get(id=tid)
        try:
            for k ,v in form_data.items():
                setattr(tp_obj,k,v)
                tp_obj.save()
            result = {"code": 0, "message": "TestPlan更新成功！"}
        except Exception as e:
            print(traceback.format_exc())
            result = {"code": 1, "message": str(e)}

        return HttpResponseRedirect('/cccs/test_plans/{3}/?status={0}&message={1}&page={2}'.
                            format(result.get("code", ""),
                                   result.get("message", ""),
                                   page,tc_id))


def run_records(request,tc_id='',t_status=''):
    '''
    run_records列表
    :param request:
    :return:
    '''
    if request.method == "GET":
        # 通知栏
        task_status = request.GET.get("task_status", "")
        status = request.GET.get("status", "")
        message = request.GET.get("message", "")
        if status.isdigit():
            result = {"code":int(status),"message":message}
        tc_id = tc_id
        t_status = t_status
        search_q = request.GET.get("q","").strip()
        page = request.GET.get('page')
        q_query = Q(Q(TestRunName__contains=search_q)|
                    Q(Status__contains=search_q)|
                    Q(JIRAID__contains=search_q)|
                    Q(FWPkgName__contains=search_q)|
                    Q(SrtPkgName__contains=search_q)
                    # Q(secsession_obj__father_session__title__contains=search_q)
                    )

        tc_obj = TestCycle.objects.get(id=tc_id)
        if t_status == "NOTSTART":
            queryset = TestRun.objects.filter(q_query,Status="NOTSTART",TCID=tc_obj).order_by('-id')
        elif t_status == "FINISHED":
            queryset = TestRun.objects.filter(q_query,Status="FINISHED",TCID=tc_obj).order_by('-id')
        elif t_status == "FAILED":
            queryset = TestRun.objects.filter(q_query,Status="FAILED",TCID=tc_obj).order_by('-id')
        elif t_status == "CANCELED":
            queryset = TestRun.objects.filter(q_query,Status="CANCELED",TCID=tc_obj).order_by('-id')
        elif t_status == "RUNNING":
            queryset = TestRun.objects.filter(q_query,Status="RUNNING",TCID=tc_obj).order_by('-id')
        else:
            queryset = TestRun.objects.filter(q_query, TCID=tc_obj).order_by('-id')
        # 加载分页器
        queryset, page_html = init_paginaion(request, queryset)

        return render(request,'cccs/run_records.html',locals())

def add_test_run(request):
    if request.method == "POST":
        tc_id = request.POST.get("tc_id")
        test_run_name = request.POST.get("TestRunName")
        trigger_time = request.POST.get("TriggerTime")
        jira_id = request.POST.get("JIRAID")
        page = request.POST.get("page")
        if test_run_name:
            try:
                TestRun.objects.create(TestRunName=test_run_name,TriggerTime=trigger_time,
                                       JIRAID=jira_id,TCID_id=tc_id )
                result = {"code": 0, "message": "TestRun创建成功!"}
            except Exception as e:
                result = {"code": 1, "message": str(e)}
        else:
            result = {"code": 1, "message": "必须指定名称!"}

templates/cccs/test_actions.html
{% load mytags  %}
<!DOCTYPE html>
<html>


<!-- Mirrored from www.zi-han.net/theme/hplus/table_data_tables.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Jan 2016 14:20:01 GMT -->
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>H+ 后台主题UI框架 - 数据表格</title>
    <meta name="keywords" content="H+后台主题,后台bootstrap框架,会员中心主题,后台HTML,响应式后台">
    <meta name="description" content="H+是一个完全响应式，基于Bootstrap3最新版本开发的扁平化主题，她采用了主流的左右两栏式布局，使用了Html5+CSS3等现代技术">

    <link rel="shortcut icon" href="../static/favicon.ico">
    <link href="/static/css/bootstrap.min14ed.css?v=3.3.6" rel="stylesheet">
    <link href="/static/css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">
    <link href="/static/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">

    <!-- Data Tables -->
    <link href="/static/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
{#    <link href="/static/css/plugins/footable/footable.core.css" rel="stylesheet">#}
    <link href="/static/css/font-awesome.min93e3.css" rel="stylesheet">
    <link href="/static/css/animate.min.css" rel="stylesheet">
    <link href="/static/css/style.min862f.css?v=4.1.0" rel="stylesheet">
    <link href="/static/css/gstyle.css" rel="stylesheet">
    <link href="/static/css/plugins/switchery/switchery.css" rel="stylesheet">
    <link href="/static/css/plugins/datapicker/datepicker3.css" rel="stylesheet">
</head>

<body class="gray-bg">
    <!--通知消息处-->
    {% if result  %}
        {% if result.code == 0 %}
            <div class="alert alert-success" style="text-align: center">执行成功:<strong>{{ result.message }}</strong></div>
        {% else %}
            <div class="alert alert-danger" style="text-align: center">执行失败:<strong>{{ result.message }}</strong></div>
        {% endif %}
    {% endif %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <ol class="breadcrumb">
                            <li><a href="/index_v3/"><span class="g_nav_font">首页</span></a></li>
                            <li>
                                <a href="/cccs/test_cycles"><span class="g_nav_font">TestCycle列表</span></a>
                            </li>
                            {% if tp_id %}
                                <li>
                                    <a href="/cccs/test_plans/{{ tp_obj.CycleID.id }}/">
                                        <span class="g_nav_font">{{ tp_obj.CycleID.CycleName }}的TestPlan详情</span>
                                    </a>
                                </li>
                                <li class="active">{{ tp_obj.CaseName }}操作记录</li>
                            {% elif tc_id %}
                                <li class="active">{{ tc_obj.CycleName }}操作记录</li>
                            {% else %}
                                <li class="active">操作记录</li>
                            {% endif %}

                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a onclick="window.location.reload()">
                                    <i class="fa fa-refresh"></i>
                                </a>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </ol>
                    </div>

                    <div class="ibox-content">
                        <div class="col-sm-12 m-b-xs" style="padding-bottom: 10px;">
                            {% if tc_obj %}
                                <form method="get" action="/cccs/test_actions/{{ tc_obj.id }}//">
                            {% elif tp_obj %}
                                <form method="get" action="/cccs/test_actions//{{ tp_obj.id }}/">
                            {% else %}
                                <form method="get" action="/cccs/test_actions///">
                            {% endif %}
                                <div class="col-sm-5">

                                </div>
                                <div class="col-sm-3" id="data_5">
                                    <div class="input-daterange input-group" id="datepicker">
                                        <input type="text" class="form-control" id="st" name="start_time" value="{{ stime }}">
                                        <span class="input-group-addon">到</span>
                                        <input type="text" class="form-control" id="et" name="end_time" value="{{ etime }}">
                                    </div>
                                </div>
                                <div class="col-sm-3 ">
                                    <input type="text" name="q"  class="form-control"  placeholder="请输入关键字进行搜索" >
                                </div>
                                <div class="col-sm-1">
                                    <button type="submit" value="搜索" class="btn btn-primary" >
                                        <i class="fa fa-search"></i>&nbsp;&nbsp;搜索
                                    </button>
                                </div>
                            </form>
                        </div>


                             <table class="table table-striped table-bordered table-hover dataTables-example" data-page-size="20">
                                 <thead>
                                    <tr>
                                        <th>操作类型</th>
                                        <th>原值</th>
                                        <th>新值</th>
                                        <th>日期</th>
                                        <th>所属TestCycle</th>
                                        <th>所属TestPlan</th>
                                        <th>操作者</th>
                                    </tr>
                                 </thead>
                                 <tbody>
                                    {% for a in queryset %}
                                        <tr>
                                            <td>
                                                <a class="btn btn-white btn-sm">{{ a.get_ActionType_display}}</a>
                                            </td>
                                            <td>{{ a.OriginalVal }} <i class="fa fa-arrow-right"></i></td>
                                            <td>{{ a.NewVal }}</td>
                                            <td>{{ a.ActionTime | date:"Y-m-d H:i:s" }}</td>
                                            <td>{{ a.CycleID.CycleName }}</td>
                                            <td>{{ a.PlanID.CaseName }}</td>
                                            <td>{{ a.ActionOP }}</td>
                                        </tr>
                                    {% endfor %}
                                 </tbody>

                             </table>
                            <div class="row">
                                <div class="col-md-6 col-md-offset-3" style="text-align: center">
                                    <ul class="pagination">
                                        {{ page_html|safe }}
                                    </ul>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 全局js -->
    <script src="/static/js/jquery.min.js?v=2.1.4"></script>
    <script src="/static/js/bootstrap.min.js?v=3.3.6"></script>

    <script src="/static/js/plugins/jeditable/jquery.jeditable.js"></script>
    <script src="/static/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/static/js/plugins/dataTables/dataTables.bootstrap.js"></script>
{#    <script src="/static/js/plugins/sweetalert/sweetalert.min.js"></script>#}
    <script src="/static/js/plugins/layer/layer.min.js"></script>
    <!-- jQuery Validation plugin javascript-->
    <script src="/static/js/plugins/validate/jquery.validate.min.js"></script>
    <script src="/static/js/plugins/validate/messages_zh.min.js"></script>
{#    <script src="/static/js/plugins/footable/footable.all.min.js"></script>#}
    <!-- 自定义js -->
    <script src="/static/js/content.min.js?v=1.0.0"></script>
    <!-- Switchery -->
    <script src="/static/js/plugins/switchery/switchery.js"></script>
    <!-- Data picker -->
    <script src="/static/js/plugins/datapicker/bootstrap-datepicker.js"></script>

    <script>
        $("#data_5 .input-daterange").datepicker(
            {
                keyboardNavigation:false,
                forceParse:false,
                autoclose:true}
            );
    </script>

    <script>
        $(document).ready(function(){$(".dataTables-example").dataTable(
            {
                "order": [], //取消加载后的第一列默认排序
                "aLengthMenu" : [10, 25, 50, 100], //更改显示记录数选项
                "iDisplayLength" : 10, //默认显示的记录数
                "paging": false,
                "searching": false
            }
        );var oTable=$("#editable").dataTable();oTable.$("td").editable("http://www.zi-han.net/theme/example_ajax.php",{"callback":function(sValue,y){var aPos=oTable.fnGetPosition(this);oTable.fnUpdate(sValue,aPos[0],aPos[1])},"submitdata":function(value,settings){return{"row_id":this.parentNode.getAttribute("id"),"column":oTable.fnGetPosition(this)[2]}},"width":"90%","height":"100%"})});function fnClickAddRow(){$("#editable").dataTable().fnAddData(["Custom row","New row","New row","New row","New row"])};
    </script>


    <script>
        $(document).ready(function() {

            $('.footable').footable();
            $('.footable2').footable();

        });

    </script>

    <script>
        {% if result %}
        swal("{{ result }}");
        {% endif %}

        </script>


    <script>
        function refresh(){
            window.location.reload();
        }
    </script>

    <script>
        $(' .del_confirm').click(function(){
            return confirm("确认要执行删除操作吗？");
        });
        $(' .js_confirm').click(function(){
            return confirm("确认执行操作吗？");
        });
    </script>

    <script>
        $(' .domain_confirm').click(function(){
            return confirm("确认要对" + $(this).attr("id") + "执行删除或停止操作吗？");
        });
    </script>

    <script>
    // 如果通知元素存在,则5秒后淡出
        if ($(".alert")){
            $(".alert").fadeOut(3000);
        }
    </script>


    <script>
        $("table").on("click",".mod-user-btn",function () {
            user_id = $(this).attr('uid');
            $("#mod_id").val("");
            $("#mod_email").val("");
            $("#mod_mobile").val("");
            $("#mod_phone").val("");
            $("#is_admin").prop("checked",false);
            $("#mod_roles option").prop("selected",false);

            $.ajax({
                url: "/rbac/users_edit",
                type: "GET",
                data: {user_id: user_id},
                dataType: 'JSON',
                success: function (arg) {
                    if (arg) {
                        console.log(arg);
                        $("#mod_id").val(arg.id);
                        $("#mod_email").val(arg.email);
                        $("#mod_mobile").val(arg.mobile);
                        $("#mod_phone").val(arg.phone);
                        if(arg.is_admin){
                            $("#is_admin").prop("checked",true);
                        }
                        $.each(arg.roles,function (k,v) {
                            $("#mod_roles [value=" + v + "]").prop("selected",true);
                        });

                    }
                }
            })
        })
    </script>

    <script>
        $("table").on('click','.mod-pwd-btn',function () {
            user_id = $(this).attr('uid');
            $("#user_id").val("");

            $.ajax({
                url: "/rbac/users_pwd",
                type: "GET",
                data: {user_id: user_id},
                dataType: 'JSON',
                success:function (arg) {
                    if(arg){$("#user_id").val(arg)}
                }
            })
        })
    </script>

</body>


<!-- Mirrored from www.zi-han.net/theme/hplus/table_data_tables.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Jan 2016 14:20:02 GMT -->
</html>